name: Dependabot auto-merge & Tests
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/semantic-notify-test.yml@main
    secrets: inherit